import type { Metadata } from "next";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import { TopNavBar } from "@/components/top-navbar"
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head></head>
    <body>
    <SidebarProvider>
      <TopNavBar />
        <AppSidebar />
        <main className="w-full pt-16 px-3">
          {children}
        </main>
    </SidebarProvider>
    </body>
  </html>
  
  );
}
